// Jenkinsfile for ParksMap
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-slave-maven-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
) {
  node('skopeo-pod') {
    echo "GUID: ${GUID}"
    echo "CLUSTER: ${CLUSTER}"

    def projectDir = "ParksMap"
    def nexusUrl = "http://nexus3-${GUID}-nexus.apps.na39.openshift.opentlc.com"
    def sonarqubeUrl = "http://sonarqube-${GUID}-sonarqube.apps.na39.openshift.opentlc.com"
    def apiUrl = "https://master.na39.openshift.opentlc.com"
    def devNamespace = "${GUID}-parks-dev"
    def prodNamespace = "${GUID}-parks-prod"
    def mvnCmd = "mvn -s ./nexus_settings.xml -f ${projectDir}/pom.xml"

    // Your Pipeline Code goes here. Make sure to use the ${GUID} and ${CLUSTER} parameters where appropriate
    // You need to build the application in directory `ParksMap`.
    // Also copy "../nexus_settings.xml" to your build directory
    // and replace 'GUID' in the file with your ${GUID} to point to >your< Nexus instance
 
    stage('Checkout Source') {
        git 'https://github.com/suejon/advanced-openshift-development-assignment'
    }

    def groupId = getGroupIdFromPom("${projectDir}/pom.xml")
    def artifactId = getArtifactIdFromPom("${projectDir}/pom.xml")
    def version = getVersionFromPom("${projectDir}/pom.xml")
    def devTag = "${version}-${BUILD_NUMBER}"
    def prodTag = "${version}"

    stage('Build jar') {
        echo "Building version ${version}"
        sh "${mvnCmd} clean package spring-boot:repackage -DskipTests -Dcom.redhat.xpaas.repo.redhatga"
    }
    
    stage('Unit Tests') {
        echo "Running Unit Tests"
        sh "${mvnCmd} test"
    }
    
    stage('Code Analysis') {
        echo "Running Code Analysis"
        sh "mvn sonar:sonar -s ./nexus_settings.xml -Dsonar.host.url=${sonarqubeUrl} -f ${projectDir}/pom.xml"
    }
    
    stage("Publish to Nexus") {
        echo "Publish to Nexus"
        sh "mvn -s ./nexus_settings.xml deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::${nexusUrl}/repository/releases -f ${projectDir}/pom.xml"
    }
    
    stage("Build and Tag Openshift Image") {
        echo "Building OpenShift container image parks-map:${devTag}"
        sh "oc start-build parks-map --from-file=${nexusUrl}/repository/releases/com/openshift/evg/roadshow/parksmap/${version}/parksmap-${version}.jar -n ${devNamespace}"
        // sh "oc start-build parks-map --from-file=http://nexus3-${GUID}-nexus.apps.na39.openshift.opentlc.com/repository/releases/com/openshift/evg/roadshow/parksmap/${version}/parksmap-${version}.jar -n ${devNamespace}"
        openshiftVerifyBuild apiURL: apiUrl, bldCfg: 'parks-map', checkForTriggeredDeployments: 'false', namespace: devNamespace, verbose: 'false', waitTime: '220000'
        // // to tag the image
        openshiftTag alias: 'false', apiURL: apiUrl, destStream: 'parks-map', destTag: devTag, destinationNamespace: devNamespace, namespace: devNamespace, srcStream: 'parks-map', srcTag: 'latest', verbose: 'false'
    }
    
    stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"
        sh "oc set image dc/parks-map parks-map=docker-registry.default.svc:5000/${devNamespace}/parks-map:${devTag} -n ${devNamespace}"
        sh "oc delete configmap parks-map-config --ignore-not-found=true -n ${devNamespace}"
        sh "oc create configmap parks-map-config --from-file=configuration/application-users.properties --from-file=configuration/application-roles.properties -n ${devNamespace}"

        openshiftDeploy apiURL: apiUrl, depCfg: "parks-map", namespace: devNamespace, verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment apiURL: apiUrl, depCfg: "parks-map", namespace: devNamespace, replicaCount: '', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'
        openshiftVerifyService apiURL: apiUrl, namespace: devNamespace, svcName: "parks-map", verbose: 'false'
    }
    
    stage('Integration Tests') {
        echo "Running Integration Tests"
        sleep 15

        echo "Get info"
        sh "curl -i -H 'Content-Leength: 0' -X GET http://parks-map-${GUID}-parks-dev.apps.na39.openshift.opentlc.com/ws/backends/list"
        echo "Loading data"
        sh "curl -i -H Content-Length: 0 -X GET http://parks-map-${GUID}-parks-dev.apps.na39.openshift.opentlc.com/ws/appname/"
    }
    
    stage('Copy Image to Nexus Docker Registry') {
        echo "Copy image to Nexus Docker Registry"
        sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:admin123 docker://docker-registry.default.svc.cluster.local:5000/${devNamespace}/parks-map:${devTag} docker://nexus-registry.${GUID}-nexus.svc.cluster.local:5000/parks-map:${devTag}"
        openshiftTag alias: 'false', destStream: 'parks-map', destTag: prodTag, destinationNamespace: devNamespace, namespace: devNamespace, srcStream: 'parks-map', srcTag: devTag, verbose: 'false'
    }
    
    def destApp = "parks-map-green"
    def activeApp = ""
    
    stage('Blue/Green Production Deployment') {
        activeApp = sh(returnStdout: true, script: "oc get route parks-map -n ${prodNamespace} -o jsonpath='{ .spec.to.name }'").trim()
        if (activeApp == "parks-map-green") {
            destApp = "parks-map-blue"
        }
        echo "Active Application:      " + activeApp
        echo "Destination Application: " + destApp

        // Update the Image on the Production Deployment Config
        sh "oc set image dc/${activeApp} ${activeApp}=docker-registry.default.svc:5000/${devNamespace}/parks-map:${prodTag} -n ${prodNamespace}"
        sh "oc set image dc/${destApp} ${destApp}=docker-registry.default.svc:5000/${devNamespace}/parks-map:${prodTag} -n ${prodNamespace}"

        // Update the Config Map which contains the users for the Parks application
        sh "oc delete configmap ${destApp}-config -n ${prodNamespace} --ignore-not-found=true"
        sh "oc create configmap ${destApp}-config --from-file=./configuration/application-users.properties --from-file=./configuration/application-roles.properties -n ${prodNamespace}"

        // Deploy the active application.
        echo "Deploying " + activeApp
        openshiftDeploy depCfg: activeApp, namespace: prodNamespace, verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment depCfg: activeApp, namespace: prodNamespace, replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'

        // Deploy the inactive application.
        echo "Deploying " + destApp
        openshiftDeploy depCfg: destApp, namespace: prodNamespace, verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment depCfg: destApp, namespace: prodNamespace, replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'

        // verify active app - green
        openshiftVerifyService namespace: prodNamespace, svcName: activeApp, verbose: 'false'
    }
    
    stage('Switch over to new Version') {
        echo "Switching Production application to ${destApp}"
        input "Switch Production?"
        echo "Switching Production application to ${destApp}."
        sh "oc patch route parks-map --patch=\'{\"spec\":{\"to\":{\"name\":\"${destApp}\"}}}\' -n ${prodNamespace}"
    }
  }
}

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
