apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mlbparks-green
  name: mlbparks-green
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mlbparks-green
    deploymentconfig: mlbparks-green
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
