apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mongo_db_services.yaml
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "mongodb-internal"
    labels:
      name: "mongodb"
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  spec:
    clusterIP: None
    ports:
      - name: mongodb
        port: 27017
    selector:
      name: "mongodb"
- kind: Service
  apiVersion: v1
  metadata:
    name: "mongodb"
    labels:
      name: "mongodb"
  spec:
    ports:
      - name: mongodb
        port: 27017
    selector:
      name: "mongodb"
