apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nationalparks-green
  name: nationalparks-green
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nationalparks-green
    deploymentconfig: nationalparks-green
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
