apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: national-parks-blue
  name: national-parks-blue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: national-parks-blue
    deploymentconfig: national-parks-blue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
