apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins-serviceaccount
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}'
    creationTimestamp: null
    name: jenkins
