kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "mlbparks-pipeline"
spec:
  source:
    git: 
      uri: https://github.com/suejon/advanced-openshift-development-assignment
    contextDir: MLBParks
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: "GUID"
        value: ""
      - name: "REPO"
        value: ""
      - name: "CLUSTER"
        value: ""
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline